;; generated by a modified makeenums.pl  ; -*- lisp -*-

(in-package "GDK")

; enumerations from "gdkcursor.h"

(deftype (cursor-type "GdkCursorType") ()
  '(enum
    (:num-glyphs  154)
    (:x-cursor  0)
    (:arrow  2)
    (:based-arrow-down  4)
    (:based-arrow-up  6)
    (:boat  8)
    (:bogosity  10)
    (:bottom-left-corner  12)
    (:bottom-right-corner  14)
    (:bottom-side  16)
    (:bottom-tee  18)
    (:box-spiral  20)
    (:center-ptr  22)
    (:circle  24)
    (:clock  26)
    (:coffee-mug  28)
    (:cross  30)
    (:cross-reverse  32)
    (:crosshair  34)
    (:diamond-cross  36)
    (:dot  38)
    (:dotbox  40)
    (:double-arrow  42)
    (:draft-large  44)
    (:draft-small  46)
    (:draped-box  48)
    (:exchange  50)
    (:fleur  52)
    (:gobbler  54)
    (:gumby  56)
    (:hand1  58)
    (:hand2  60)
    (:heart  62)
    (:icon  64)
    (:iron-cross  66)
    (:left-ptr  68)
    (:left-side  70)
    (:left-tee  72)
    (:leftbutton  74)
    (:ll-angle  76)
    (:lr-angle  78)
    (:man  80)
    (:middlebutton  82)
    (:mouse  84)
    (:pencil  86)
    (:pirate  88)
    (:plus  90)
    (:question-arrow  92)
    (:right-ptr  94)
    (:right-side  96)
    (:right-tee  98)
    (:rightbutton  100)
    (:rtl-logo  102)
    (:sailboat  104)
    (:sb-down-arrow  106)
    (:sb-h-double-arrow  108)
    (:sb-left-arrow  110)
    (:sb-right-arrow  112)
    (:sb-up-arrow  114)
    (:sb-v-double-arrow  116)
    (:shuttle  118)
    (:sizing  120)
    (:spider  122)
    (:spraycan  124)
    (:star  126)
    (:target  128)
    (:tcross  130)
    (:top-left-arrow  132)
    (:top-left-corner  134)
    (:top-right-corner  136)
    (:top-side  138)
    (:top-tee  140)
    (:trek  142)
    (:ul-angle  144)
    (:umbrella  146)
    (:ur-angle  148)
    (:watch  150)
    (:xterm  152)
    :last-cursor
    (:cursor-is-pixmap  -1 )))

; enumerations from "gdkdnd.h"

(deftype (drag-action "GdkDragAction") ()
  '(flags
    (:default  0)
    (:copy  1)
    (:move  2)
    (:link  3)
    (:private  4)
    (:ask  5 )))

(deftype (drag-protocol "GdkDragProtocol") ()
  '(enum
    :motif
    :xdnd
    :rootwin
    :none
    :win32-dropfiles
    :ole2
    :local))

; enumerations from "gdkevents.h"

(deftype (filter-return "GdkFilterReturn") ()
  '(enum
    :continue
    :translate
    :remove))

(deftype (event-type "GdkEventType") ()
  '(enum
    (:nothing  -1)
    (:delete  0)
    (:destroy  1)
    (:expose  2)
    (:motion-notify  3)
    (:button-press  4)
    (:2button-press  5)
    (:3button-press  6)
    (:button-release  7)
    (:key-press  8)
    (:key-release  9)
    (:enter-notify  10)
    (:leave-notify  11)
    (:focus-change  12)
    (:configure  13)
    (:map  14)
    (:unmap  15)
    (:property-notify  16)
    (:selection-clear  17)
    (:selection-request  18)
    (:selection-notify  19)
    (:proximity-in  20)
    (:proximity-out  21)
    (:drag-enter  22)
    (:drag-leave  23)
    (:drag-motion  24)
    (:drag-status  25)
    (:drop-start  26)
    (:drop-finished  27)
    (:client-event  28)
    (:visibility-notify  29)
    (:no-expose  30)
    (:scroll  31 )))

(deftype (event-mask "GdkEventMask") ()
  '(flags
    (:exposure-mask  1)
    (:pointer-motion-mask  2)
    (:pointer-motion-hint-mask  3)
    (:button-motion-mask  4)
    (:button1-motion-mask  5)
    (:button2-motion-mask  6)
    (:button3-motion-mask  7)
    (:button-press-mask  8)
    (:button-release-mask  9)
    (:key-press-mask  10)
    (:key-release-mask  11)
    (:enter-notify-mask  12)
    (:leave-notify-mask  13)
    (:focus-change-mask  14)
    (:structure-mask  15)
    (:property-change-mask  16)
    (:visibility-notify-mask  17)
    (:proximity-in-mask  18)
    (:proximity-out-mask  19)
    (:substructure-mask  20)
    (:scroll-mask  21)
;    (:all-events-mask  #x3FFFFE )
   ))

(deftype (visibility-state "GdkVisibilityState") ()
  '(enum
    :unobscured
    :partial
    :fully-obscured))

(deftype (scroll-direction "GdkScrollDirection") ()
  '(enum
    :up
    :down
    :left
    :right))

(deftype (notify-type "GdkNotifyType") ()
  '(enum
    (:ancestor  0)
    (:virtual  1)
    (:inferior  2)
    (:nonlinear  3)
    (:nonlinear-virtual  4)
    (:unknown  5 )))

(deftype (crossing-mode "GdkCrossingMode") ()
  '(enum
    :normal
    :grab
    :ungrab))

(deftype (property-state "GdkPropertyState") ()
  '(enum
    :new-value
    :delete))

; enumerations from "gdkfont.h"

(deftype (font-type "GdkFontType") ()
  '(enum
    :font
    :fontset))

; enumerations from "gdkgc.h"

(deftype (cap-style "GdkCapStyle") ()
  '(enum
    :not-last
    :butt
    :round
    :projecting))

(deftype (fill "GdkFill") ()
  '(enum
    :solid
    :tiled
    :stippled
    :opaque-stippled))

(deftype (gc-function "GdkFunction") ()
  '(enum
    :copy
    :invert
    :xor
    :clear
    :and
    :and-reverse
    :and-invert
    :noop
    :or
    :equiv
    :or-reverse
    :copy-invert
    :or-invert
    :nand
    :nor
    :set))

(deftype (join-style "GdkJoinStyle") ()
  '(enum
    :miter
    :round
    :bevel))

(deftype (line-style "GdkLineStyle") ()
  '(enum
    :solid
    :on-off-dash
    :double-dash))

(deftype (subwindow-mode "GdkSubwindowMode") ()
  '(enum
    (:clip-by-children  0)
    (:include-inferiors  1 )))

(deftype (g-c-values-mask "GdkGCValuesMask") ()
  '(flags
    (:foreground  0)
    (:background  1)
    (:font  2)
    (:function  3)
    (:fill  4)
    (:tile  5)
    (:stipple  6)
    (:clip-mask  7)
    (:subwindow  8)
    (:ts-x-origin  9)
    (:ts-y-origin  10)
    (:clip-x-origin  11)
    (:clip-y-origin  12)
    (:exposures  13)
    (:line-width  14)
    (:line-style  15)
    (:cap-style  16)
    (:join-style  17 )))

; enumerations from "gdkimage.h"

(deftype (image-type "GdkImageType") ()
  '(enum
    :normal
    :shared
    :fastest
    :shared-pixmap))

; enumerations from "gdkim.h"

(deftype (im-style "GdkIMStyle") ()
  '(flags
;    (:preedit-area  #x0001)
;    (:preedit-callbacks  #x0002)
;    (:preedit-position  #x0004)
;    (:preedit-nothing  #x0008)
;    (:preedit-none  #x0010)
;    (:preedit-mask  #x001f)
;    (:status-area  #x0100)
;    (:status-callbacks  #x0200)
;    (:status-nothing  #x0400)
;    (:status-none  #x0800)
;    (:status-mask  #x0f00  )
   ))

; (deftype (ic-attributes-type "GdkICAttributesType") ()
;   '(flags
;     (:style  0)
;     (:client-window  1)
;     (:focus-window  2)
;     (:filter-events  3)
;     (:spot-location  4)
;     (:line-spacing  5)
;     (:cursor  6)
;     (:preedit-fontset  10)
;     (:preedit-area  11)
;     (:preedit-area-needed  12)
;     (:preedit-foreground  13)
;     (:preedit-background  14)
;     (:preedit-pixmap  15)
;     (:preedit-colormap  16)
;     (:status-fontset  21)
;     (:status-area  22)
;     (:status-area-needed  23)
;     (:status-foreground  24)
;     (:status-background  25)
;     (:status-pixmap  26)
;     (:status-colormap  27)
; ;    (:all-req  GDK_IC_STYLE | )
;     :client-window
; ;    (:preedit-area-req  GDK_IC_PREEDIT_AREA |  )
;     :preedit-fontset
; ;    (:preedit-position-req  GDK_IC_PREEDIT_AREA | GDK_IC_SPOT_LOCATION | )
;     :preedit-fontset
; ;    (:status-area-req  GDK_IC_STATUS_AREA |  )
;     :status-fontset))

; enumerations from "gdkinput.h"

(deftype (extension-mode "GdkExtensionMode") ()
  '(enum
    :none
    :all
    :cursor))

(deftype (input-source "GdkInputSource") ()
  '(enum
    :mouse
    :pen
    :eraser
    :cursor))

(deftype (input-mode "GdkInputMode") ()
  '(enum
    :disabled
    :screen
    :window))

(deftype (axis-use "GdkAxisUse") ()
  '(enum
    :ignore
    :x
    :y
    :pressure
    :xtilt
    :ytilt
    :wheel
    :last))

; enumerations from "gdkpixbuf.h"

; (deftype (pixbuf-alpha-mode "GdkPixbufAlphaMode") ()
;   '(enum
;     :bilevel
;     :full))

; enumerations from "gdkproperty.h"

(deftype (prop-mode "GdkPropMode") ()
  '(enum
    :replace
    :prepend
    :append))

; enumerations from "gdkregion.h"

(deftype (fill-rule "GdkFillRule") ()
  '(enum
    :even-odd-rule
    :winding-rule))

(deftype (overlap-type "GdkOverlapType") ()
  '(enum
    :in
    :out
    :part))

; enumerations from "gdkrgb.h"

(deftype (rgb-dither "GdkRgbDither") ()
  '(enum
    :none
    :normal
    :max))

; enumerations from "gdkselection.h"

(deftype (selection "GdkSelection") ()
  '(enum
    (:primary  1)
    (:secondary  2 )))

(deftype (target "GdkTarget") ()
  '(enum
    (:bitmap  5)
    (:colormap  7)
    (:drawable  17)
    (:pixmap  20)
    (:string  31 )))

(deftype (selection-type "GdkSelectionType") ()
  '(enum
    (:atom  4)
    (:bitmap  5)
    (:colormap  7)
    (:drawable  17)
    (:integer  19)
    (:pixmap  20)
    (:window  33)
    (:string  31 )))

; enumerations from "gdktypes.h"

(deftype (byte-order "GdkByteOrder") ()
  '(enum
    :lsb-first
    :msb-first))

(deftype (modifier-type "GdkModifierType") ()
  '(flags
    (:shift-mask  0)
    (:lock-mask  1)
    (:control-mask  2)
    (:mod1-mask  3)
    (:mod2-mask  4)
    (:mod3-mask  5)
    (:mod4-mask  6)
    (:mod5-mask  7)
    (:button1-mask  8)
    (:button2-mask  9)
    (:button3-mask  10)
    (:button4-mask  11)
    (:button5-mask  12)
    (:release-mask  31)
;    (:modifier-mask  GDK_RELEASE_MASK | #x1fff )
   ))

(deftype (input-condition "GdkInputCondition") ()
  '(flags
    (:read  0)
    (:write  1)
    (:exception  2 )))

(deftype (status "GdkStatus") ()
  '(enum
    (:ok  0)
    (:error  -1)
    (:error-param  -2)
    (:error-file  -3)
    (:error-mem  -4 )))

(deftype (grab-status "GdkGrabStatus") ()
  '(enum
    (:success  0)
    (:already-grabbed  1)
    (:invalid-time  2)
    (:not-viewable  3)
    (:frozen  4 )))

; enumerations from "gdkvisual.h"

(deftype (visual-type "GdkVisualType") ()
  '(enum
    :static-gray
    :grayscale
    :static-color
    :pseudo-color
    :true-color
    :direct-color))

; enumerations from "gdkwindow.h"

(deftype (window-class "GdkWindowClass") ()
  '(enum
    :output
    :only))

(deftype (window-type "GdkWindowType") ()
  '(enum
    :root
    :toplevel
    :child
    :dialog
    :temp
    :foreign))

(deftype (window-attributes-type "GdkWindowAttributesType") ()
  '(flags
    (:title  1)
    (:x  2)
    (:y  3)
    (:cursor  4)
    (:colormap  5)
    (:visual  6)
    (:wmclass  7)
    (:noredir  8 )))

(deftype (window-hints "GdkWindowHints") ()
  '(flags
    (:pos  0)
    (:min-size  1)
    (:max-size  2)
    (:base-size  3)
    (:aspect  4)
    (:resize-inc  5 )))

(deftype (wm-decoration "GdkWMDecoration") ()
  '(flags
    (:all  0)
    (:border  1)
    (:resizeh  2)
    (:title  3)
    (:menu  4)
    (:minimize  5)
    (:maximize  6 )))

(deftype (wm-function "GdkWMFunction") ()
  '(flags
    (:all  0)
    (:resize  1)
    (:move  2)
    (:minimize  3)
    (:maximize  4)
    (:close  5 )))
