(defpackage "GTK"
  (:use "GLIB" "COMMON-LISP" "PCL" "ALIEN" "AUTOEXPORT")
  (:shadowing-import-from "GLIB" "DEFTYPE")
  (:shadowing-import-from "PCL"
   "CLASS-NAME" "BUILT-IN-CLASS" "CLASS-OF" "FIND-CLASS" "LOCATION"
   "ALLOCATION" "DIRECT-SLOTS")
  (:export "OBJECT" "OBJECT-ARG" "OBJECT-SINK")
  (:export "REGISTER-USER-DATA" "FIND-USER-DATA" "REGISTER-CALLBACK-FUNCTION"
	   "*CALLBACK-MARSHAL*" "*DESTROY-MARSHAL*")
  (:export "EVENTS-PENDING-P" "MAIN-DO-EVENT" "MAIN" "MAIN-LEVEL" "MAIN-QUIT"
	   "MAIN-ITERATION" "MAIN-ITERATE-ALL")
  (:export "SIGNAL-EMIT-STOP" "SIGNAL-CONNECT" "SIGNAL-DISCONNECT"
	   "SIGNAL-HANDLER-BLOCK" "SIGNAL-HANDLER-UNBLOCK")
  (:export "OBJECT-CLASS" "WIDGET-CLASS" "CONTAINER-CLASS" "CHILD-CLASS"))
 