;; generated by a modified makeenums.pl  ; -*- lisp -*-
;; but edited by hand

(in-package "GTK")

; enumerations from "gtkaccelgroup.h"

(deftype (accel-flags "GtkAccelFlags") ()
  '(flags
   (:visible  0)
   (:signal-visible  1)
   (:locked  2)
;   (:mask  #x07 )
  ))

; enumerations from "gtkcalendar.h"

(deftype (calendar-display-options "GtkCalendarDisplayOptions") ()
  '(flags
   (:show-heading  0)
   (:show-day-names  1)
   (:no-month-change  2)
   (:show-week-numbers  3)
   (:week-start-monday  4 )))

; enumerations from "gtkclist.h"

(deftype (cell-type "GtkCellType") ()
  '(enum
   :empty
   :text
   :pixmap
   :pixtext
   :widget))

(deftype (c-list-drag-pos "GtkCListDragPos") ()
  '(enum
   :none
   :before
   :into
   :after))

(deftype (button-action "GtkButtonAction") ()
  '(flags
;   (:ignored  0)
   (:selects  0)
   (:drags  1)
   (:expands  2 )))

; enumerations from "gtkctree.h"

(deftype (ctree-pos "GtkCTreePos") ()
  '(enum
   :before
   :as-child
   :after))

(deftype (ctree-line-style "GtkCTreeLineStyle") ()
  '(enum
   :none
   :solid
   :dotted
   :tabbed))

(deftype (ctree-expander-style "GtkCTreeExpanderStyle") ()
  '(enum
   :none
   :square
   :triangle
   :circular))

(deftype (ctree-expansion-type "GtkCTreeExpansionType") ()
  '(enum
   :expand
   :expand-recursive
   :collapse
   :collapse-recursive
   :toggle
   :toggle-recursive))

; enumerations from "gtkdebug.h"

(deftype (debug-flag "GtkDebugFlag") ()
  '(flags
   (:objects  0)
   (:misc  1)
   (:signals  2)
   (:dnd 3)
   (:plugsocket 4)
   (:text 5 )))

; enumerations from "gtkdnd.h"

(deftype (dest-defaults "GtkDestDefaults") ()
  '(flags
   (:motion  0)
   (:highlight  1)
   (:drop  2)
;  (:all  #x07 )
  ))

(deftype (target-flags "GtkTargetFlags") ()
  '(flags
   (:same-app  0)
   (:same-widget  1  )))

; enumerations from "gtkenums.h"

(deftype (arrow-type "GtkArrowType") ()
  '(enum
   :up
   :down
   :left
   :right))

(deftype (attach-options "GtkAttachOptions") ()
  '(flags
   (:expand  0)
   (:shrink  1)
   (:fill  2 )))

(deftype (button-box-style "GtkButtonBoxStyle") ()
  '(enum
   :default-style
   :spread
   :edge
   :start
   :end))

(deftype (curve-type "GtkCurveType") ()
  '(enum
   :linear
   :spline
   :free))

(deftype (direction-type "GtkDirectionType") ()
  '(enum
   :tab-forward
   :tab-backward
   :up
   :down
   :left
   :right))

(deftype (text-direction "GtkTextDirection") ()
  '(enum
   :none
   :ltr
   :rtl))

(deftype (justification "GtkJustification") ()
  '(enum
   :left
   :right
   :center
   :fill))

(deftype (match-type "GtkMatchType") ()
  '(enum
   :all
   :all-tail
   :head
   :tail
   :exact
   :last))

(deftype (menu-direction-type "GtkMenuDirectionType") ()
  '(enum
   :parent
   :child
   :next
   :prev))

(deftype (menu-factory-type "GtkMenuFactoryType") ()
  '(enum
   :menu
   :menu-bar
   :option-menu))

(deftype (metric-type "GtkMetricType") ()
  '(enum
   :pixels
   :inches
   :centimeters))

(deftype (orientation "GtkOrientation") ()
  '(enum
   :horizontal
   :vertical))

(deftype (corner-type "GtkCornerType") ()
  '(enum
   :top-left
   :bottom-left
   :top-right
   :bottom-right))

(deftype (pack-type "GtkPackType") ()
  '(enum
   :start
   :end))

(deftype (path-priority-type "GtkPathPriorityType") ()
  '(enum
   (:lowest  0)
   (:gtk  4)
   (:application  8)
   (:rc  12)
   (:highest  15)
;  (:mask  #x0f )
   ))

(deftype (path-type "GtkPathType") ()
  '(enum
   :widget
   :widget-class
   :class))

(deftype (policy-type "GtkPolicyType") ()
  '(enum
   :always
   :automatic
   :never))

(deftype (position-type "GtkPositionType") ()
  '(enum
   :left
   :right
   :top
   :bottom))

(deftype (preview-type "GtkPreviewType") ()
  '(enum
   :color
   :grayscale))

(deftype (relief-style "GtkReliefStyle") ()
  '(enum
   :normal
   :half
   :none))

(deftype (resize-mode "GtkResizeMode") ()
  '(enum
   :parent
   :queue
   :immediate))

(deftype (signal-run-type "GtkSignalRunType") ()
  '(flags
   (:first  0)
   (:last  1)
;   (:both  (GTK_RUN_FIRST | GTK_RUN_LAST))
   (:no-recurse  2)
   (:action  3)
   (:no-hooks  4 )))

(deftype (scroll-type "GtkScrollType") ()
  '(enum
   :none
   :step-backward
   :step-forward
   :page-backward
   :page-forward
   :jump))

(deftype (selection-mode "GtkSelectionMode") ()
  '(enum
   :single
   :browse
   :multiple
   :extended))

(deftype (shadow-type "GtkShadowType") ()
  '(enum
   :none
   :in
   :out
   :etched-in
   :etched-out))

(deftype (state-type "GtkStateType") ()
  '(enum
   :normal
   :active
   :prelight
   :selected
   :insensitive))

(deftype (submenu-direction "GtkSubmenuDirection") ()
  '(enum
   :left
   :right))

(deftype (submenu-placement "GtkSubmenuPlacement") ()
  '(enum
   :top-bottom
   :left-right))

(deftype (toolbar-style "GtkToolbarStyle") ()
  '(enum
   :icons
   :text
   :both
   :both-horiz))

(deftype (trough-type "GtkTroughType") ()
  '(enum
   :none
   :start
   :end
   :jump))

(deftype (update-type "GtkUpdateType") ()
  '(enum
   :continuous
   :discontinuous
   :delayed))

(deftype (visibility "GtkVisibility") ()
  '(enum
   :none
   :partial
   :full))

(deftype (window-position "GtkWindowPosition") ()
  '(enum
   :none
   :center
   :mouse
   :center-always))

(deftype (window-type "GtkWindowType") ()
  '(enum
   :toplevel
   :dialog
   :popup))

(deftype (sort-type "GtkSortType") ()
  '(enum
   :ascending
   :descending))

; enumerations from "gtkobject.h"

(deftype (object-flags "GtkObjectFlags") ()
  '(flags
   (:destroyed  0)
   (:floating  1)
   (:connected  2)
   (:constructed  3 )))

(deftype (arg-flags "GtkArgFlags") ()
  '(flags
   (:readable  0)
   (:writable  1)
   (:construct  2)
   (:construct-only  3)
   (:child-arg  4)
;   (:mask  #x1f)
;   (:readwrite  GTK_ARG_READABLE | GTK_ARG_WRITABLE )
  ))

; enumerations from "gtkpacker.h"

(deftype (packer-options "GtkPackerOptions") ()
  '(flags
   (:expand  0)
   (:fill-x  1)
   (:fill-y  2 )))

(deftype (side-type "GtkSideType") ()
  '(enum
   :top
   :bottom
   :left
   :right))

(deftype (anchor-type "GtkAnchorType") ()
  '(enum
   :center
   :north
   :north-west
   :north-east
   :south
   :south-west
   :south-east
   :west
   :east
;   (:n 	GTK_ANCHOR_NORTH)
;   (:nw 	GTK_ANCHOR_NORTH_WEST)
;   (:ne 	GTK_ANCHOR_NORTH_EAST)
;   (:s 	GTK_ANCHOR_SOUTH)
;   (:sw 	GTK_ANCHOR_SOUTH_WEST)
;   (:se 	GTK_ANCHOR_SOUTH_EAST)
;   (:w 	GTK_ANCHOR_WEST)
;   (:e 	GTK_ANCHOR_EAST )
   ))

; enumerations from "gtkprivate.h"

(deftype (private-flags "GtkPrivateFlags") ()
  '(flags
   (:user-style  0)
   (:resize-pending  2)
   (:resize-needed  3)
   (:leave-pending  4)
   (:has-shape-mask  5)
   (:in-reparent  6)
   (:direction-set  7)
   (:direction-ltr  8)))

; enumerations from "gtkprogressbar.h"

(deftype (progress-bar-style "GtkProgressBarStyle") ()
  '(enum
   :continuous
   :discrete))

(deftype (progress-bar-orientation "GtkProgressBarOrientation") ()
  '(enum
   :left-to-right
   :right-to-left
   :bottom-to-top
   :top-to-bottom))

; enumerations from "gtkrc.h"

(deftype (rc-flags "GtkRcFlags") ()
  '(flags
   (:fg  0)
   (:bg  1)
   (:text  2)
   (:base  3 )))

(deftype (rc-token-type "GtkRcTokenType") ()
  '(enum
   (:invalid  G_TOKEN_LAST)
   :include
   :normal
   :active
   :prelight
   :selected
   :insensitive
   :fg
   :bg
   :text
   :base
   :xthickness
   :ythickness
   :font
   :fontset
   :font-name
   :bg-pixmap
   :pixmap-path
   :style
   :binding
   :bind
   :widget
   :widget-class
   :class
   :lowest
   :gtk
   :application
   :rc
   :highest
   :engine
   :module-path
;   :last
   ))

; enumerations from "gtkspinbutton.h"

(deftype (spin-button-update-policy "GtkSpinButtonUpdatePolicy") ()
  '(enum
   :always
   :if-valid))

(deftype (spin-type "GtkSpinType") ()
  '(enum
   :step-forward
   :step-backward
   :page-forward
   :page-backward
   :home
   :end
   :user-defined))

; enumerations from "gtktexttag.h"

(deftype (wrap-mode "GtkWrapMode") ()
  '(enum
   :none
   :char
   :word))

; enumerations from "gtktexttypes.h"

(deftype text-tab-align
;  (text-tab-align "GtkTextTabAlign")
  ()
  '(enum
   :left
   :right
   :center
   :numeric))

; enumerations from "gtktextview.h"

(deftype (text-view-movement-step "GtkTextViewMovementStep") ()
  '(enum
   :char
   :positions
   :word
   :line
   :paragraph
   :paragraph-ends
   :buffer-ends))

(deftype (text-view-scroll-type "GtkTextViewScrollType") ()
  '(enum
   :to-top
   :to-bottom
   :page-down
   :page-up))

(deftype (text-view-delete-type "GtkTextViewDeleteType") ()
  '(enum
   :char
   :half-word
   :whole-word
   :half-line
   :whole-line
   :half-paragraph
   :whole-paragraph
   :whitespace
   :whitespace-leave-one))

; enumerations from "gtktoolbar.h"

(deftype (toolbar-child-type "GtkToolbarChildType") ()
  '(enum
   :space
   :button
   :togglebutton
   :radiobutton
   :widget))

(deftype (toolbar-space-style "GtkToolbarSpaceStyle") ()
  '(enum
   :empty
   :line))

; enumerations from "gtktree.h"

(deftype (tree-view-mode "GtkTreeViewMode") ()
  '(enum
   :line
   :item))

; enumerations from "gtkwidget.h"

(deftype (widget-flags "GtkWidgetFlags") ()
  '(flags
   (:toplevel  4)
   (:no-window  5)
   (:realized  6)
   (:mapped  7)
   (:visible  8)
   (:sensitive  9)
   (:parent-sensitive  10)
   (:can-focus  11)
   (:has-focus  12)
   (:can-default  13)
   (:has-default  14)
   (:has-grab  15)
   (:rc-style  16)
   (:composite-child  17)
   (:no-reparent  18)
   (:app-paintable  19)
   (:receives-default  20)
   (:double-buffered  21 )))
