(defpackage "GLADE-XML"
  (:use "COMMON-LISP" "CLG-UTILS" "GFFI" "GLIB" "GTK" "S-XML" "PARSE-NUMBER"
	#+sbcl"SB-MOP")
  (:export "BUILD-INTERFACE" "LOAD-INTERFACE" "ADD-CHILD"
	   "PARSE-VALUE" "GET-PROPERTY-INFO"))
